# A terminal colour scheme in Ghostty's format, vendored from
# iTerm2-Color-Schemes into `Rori.themes_directory`. Each theme overrides the
# host's semantic color tokens (--color-*), so it re-colours the whole app; the
# desk's own --rori-* tokens derive from them (rori/_init.css); `bin/rails rori:themes:build` compiles them all into
# `Rori.themes_stylesheet`. Drop in another file and rebuild to add one.
class Rori::Theme
  # Window gutters sit this much darker than windows, like the default theme.
  CANVAS_DARKEN = 0.04

  attr_reader :name, :colors

  class << self
    # Bundled themes plus the app's `Rori.themes_folder`; an app theme with a
    # bundled theme's name replaces it.
    def all = (bundled + local).index_by(&:slug).values.sort_by(&:name)

    def bundled = load(Rori.themes_directory)

    def local = Rori.themes_folder ? load(Rails.root.join(Rori.themes_folder)) : []

    def find(slug) = slug.presence && all.find { it.slug == slug }

    def from_file(path)
      colors = path.readlines.each_with_object({}) do |line, colors|
        key, value = line.split("=", 2).map(&:strip)
        next if value.blank?

        if key == "palette"
          index, hex = value.split("=", 2)
          colors[index.to_i] = hex.strip
        else
          colors[key] = value
        end
      end
      new(path.basename.to_s, colors)
    end

    # The compiled file holds the bundled themes; app themes are rendered into
    # the shell instead (Rori::ThemeHelper), so apps never write into the gem.
    def stylesheet
      <<~CSS
        /* Generated by `bin/rails rori:themes:build` from vendor/themes/ghostty — do not edit. */
        #{css(bundled)}
      CSS
    end

    def css(themes) = "@layer rori.themes {\n#{themes.map(&:to_css).join("\n")}}"

    private
      def load(directory) = Pathname(directory).glob("*").select(&:file?).sort.map { from_file(it) }
  end

  def initialize(name, colors)
    @name = name
    @colors = colors
  end

  def slug = name.parameterize

  def dark? = background.lightness < 0.6

  def tokens
    {
      "--color-canvas" => background.darken(CANVAS_DARKEN),
      "--color-surface" => background,
      "--color-ink" => color("foreground"),
      "--color-danger" => color(1),
      "--color-success" => color(2),
      "--color-warning" => color(3),
      "--color-info" => color(4)
    }
  end

  def to_css
    declarations = [ "color-scheme: #{dark? ? "dark" : "light"}", *tokens.map { |token, value| "#{token}: #{value}" } ]
    <<~CSS.indent(2)
      :root[data-theme="#{slug}"] {
      #{declarations.map { "  #{it};" }.join("\n")}
      }
    CSS
  end

  private
    def background = color("background")

    def color(key) = Color.from_hex(colors.fetch(key))
end
